org: yugasun
app: fullstack-serverless-db
stage: dev

component: postgresql
name: fullstackDB

inputs:
  region: ${env:REGION}
  zone: ${env:ZONE}
  dBInstanceName: ${name}
  vpcConfig:
    vpcId: ${env:VPC_ID}
    subnetId: ${env:SUBNET_ID}
  extranetAccess: false
